server:
  port: 11000

spring:
  application:
    name: oauth2-resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:10000/.well-known/jwks.json
  #微服务配置
  cloud:
    nacos:
      server-addr: nacos:8848
  zipkin:
    base-url: http://zipkin:9411/
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: *
  endpoint:
    shutdown:
      enabled: true
      